### ISSUE TITLE
Unable to import ZIP after clearing currently-imported images

### ISSUE THREAD

**Issue by zpw6737** [photostack/photostack#85]
Steps to reproduce:

1. Choose "Import" and "Import images from ZIP/container file".
2. Select a ZIP and photos will import fine.
3. Make changes and export as ZIP.
4. Choose "Clear".
5. Choose "Import images from ZIP/container file" again.
6. After selecting ZIP, nothing will happen.

**Comment by corbindavenport** [comment]
This is fixed now.
